### ISSUE TITLE
Issue with APA Formatting when no author is specified

### ISSUE THREAD

**Issue by QaidVoid** [typst/citationberg#4]
### Description

When using references without authors, the generated output format is incorrect.

Example bib,
```bib
@misc{sdm,
  title = {Definition and objectives of systems development},
  url = {https://www.opentextbooks.org.hk/ditatopic/25323},
  language = {en},
  urldate = {2023-11-24},
  journal = {Open Textbooks for Hong Kong},
  date = {2016-01-19},
}
```

Expected Citation Output:
(_Definition and objectives of systems development_, 2016)

Actual Citation Output:
(2016)

Expected Bibliography Output:
Definition and Objectives of Systems Development. (2016, January 19). Open Textbooks for Hong Kong. https://www.opentextbooks.org.hk/ditatopic/25323

Actual Bibliography Output:
(2016, January 19). https://www.opentextbooks.org.hk/ditatopic/25323

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by marvin-kolja** [comment]
Do you happen to have any news on this? This is specifically a problem for online resources that often do not have an author.

**Comment by marvin-kolja** [comment]
Yes, substitution doesn't work as intended. If we have the following:

```bib
@online{someKey,
  title = {Some Title},
  url = {https://google.com},
  urldate = {2024-03-11},
}
```

Then it will produce:

```
Retrieved March 11, 2024, from https://google.com/
```

As soon as I add an editor or author...

```bib
@online{someKey,
  editor = {Mustermann, Max},
  title = {Some Title},
  url = {https://google.com},
  urldate = {2024-03-11},
}
```

...it will produce the following:

```
Mustermann, M.  (Ed.). Some Title. Retrieved March 11, 2024, from https://google.com/
```

For the APA 7th edition, maybe the `choose` is not handled correctly (https://github.com/citation-style-language/styles/blob/0a035d78a6e922f392ccb6af8a6972e5302e02bb/apa.csl#L131-L149 and https://github.com/citation-style-language/styles/blob/0a035d78a6e922f392ccb6af8a6972e5302e02bb/apa.csl#L163-L173)?

**Comment by AstrickHarren** [comment]
I found the problem is due to `substitute` and `choose` working together. (Its actually a problem of `typst/hayagriva`)

1. `substitute` will cause any subsequent `query` to variables, in this case, the `title`, suppressed if that variable is queried once before.
2. `choose` actually calls `query` to `title`  two times, the first time to find out which branch makes sense and the second to render. 
3. therefore the second time is suppressed and resulting in no title. 

A simple fix can be to do a silent lookup on the first `query` of `choose`, much like what is done in `Test::will_have_info(..)`. 

This is the output from OP's bib after applying the fix: 
```
Definition and objectives of systems development. (2016, January 19). https://www.opentextbooks.org.hk/ditatopic/25323
```

However, the `journal` part does not seem to be there, which I think is not there even with author specified.
